#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# SecurEra DAM — turnkey installer for a blank Linux host (source-less).
#
# Deploys the PRE-BUILT image bundle. No source code required on this host — just
# Docker + the bundle. Run this from the directory that holds:
#     docker-compose.prod.yml   config/   .env(optional)   dam-images-*.tar.gz(optional)
#
#   sudo ./install.sh                       # air-gapped: loads images from the tarball
#   REGISTRY=myreg.example/dam TAG=v1 \
#     sudo -E ./install.sh                   # pull from a registry instead of a tarball
#
# It: pre-flight-checks the host → installs Docker if missing → loads the images →
# generates a .env with fresh secrets (or reuses yours) → brings the stack up →
# waits for health → prints next steps. Idempotent: safe to re-run.
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$DIR"
COMPOSE="docker-compose.prod.yml"
ENV_FILE=".env"
REGISTRY="${REGISTRY:-}"; TAG="${TAG:-prod}"
c_ok(){ printf '  \033[32m✓\033[0m %s\n' "$*"; }
c_warn(){ printf '  \033[33m!\033[0m %s\n' "$*"; }
c_err(){ printf '  \033[31m✗\033[0m %s\n' "$*"; }
step(){ printf '\n\033[1m== %s ==\033[0m\n' "$*"; }
die(){ c_err "$*"; exit 1; }

# ── 0. sanity: the bundle is present ────────────────────────────────────────
step "0 · bundle check"
[ -f "$COMPOSE" ] || die "$COMPOSE not found — run this from the bundle directory."
[ -d config ]     || die "config/ not found — ship it alongside the compose file."
c_ok "compose + config present"

# ── 1. host pre-flight (go / no-go) ─────────────────────────────────────────
step "1 · host pre-flight"
[ "$(uname -m)" = "x86_64" ] && c_ok "arch x86_64" || die "arch $(uname -m) unsupported (need x86_64)"
CPU=$(nproc); [ "$CPU" -ge 4 ] && c_ok "cpu ${CPU} cores" || c_warn "cpu ${CPU} cores (4+ recommended)"
RAMG=$(( $(getconf _PHYS_PAGES) * $(getconf PAGE_SIZE) / 1024/1024/1024 ))
[ "$RAMG" -ge 8 ] && c_ok "ram ${RAMG} GB" || c_warn "ram ${RAMG} GB (8+ recommended, 16 for load)"
FREEG=$(df -BG --output=avail / | tail -1 | tr -dc '0-9')
[ "$FREEG" -ge 50 ] && c_ok "disk ${FREEG} GB free" || c_warn "disk ${FREEG} GB free (50+ recommended — ClickHouse grows)"
[ "$(id -u)" = "0" ] || die "run with sudo (needs to install Docker + bind low ports)"

# ── 2. Docker + compose ─────────────────────────────────────────────────────
step "2 · docker engine"
if docker version >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
  c_ok "docker $(docker version -f '{{.Server.Version}}') + compose present"
else
  c_warn "installing Docker via get.docker.com …"
  curl -fsSL https://get.docker.com | sh >/dev/null 2>&1
  systemctl enable --now docker >/dev/null 2>&1 || true
  docker compose version >/dev/null 2>&1 || die "Docker install failed"
  c_ok "docker installed"
fi

# ── 3. images: load the tarball, or pull from a registry ────────────────────
step "3 · images"
if [ -n "$REGISTRY" ]; then
  c_ok "using registry $REGISTRY (run 'docker login' first if it is private)"
else
  TARBALL="$(ls -1 dam-images-*.tar.gz dist/dam-images-*.tar.gz 2>/dev/null | head -1 || true)"
  [ -n "$TARBALL" ] || die "no dam-images-*.tar.gz in $DIR or $DIR/dist and no REGISTRY set"
  c_warn "loading $TARBALL (this is the biggest step) …"
  gunzip -c "$TARBALL" | docker load | sed 's/^/    /'
  c_ok "images loaded"
fi

# ── 4. .env: reuse yours, or generate one with fresh secrets ────────────────
step "4 · configuration (.env)"
if [ -f "$ENV_FILE" ] && grep -q '^CREDENTIAL_ENCRYPTION_KEY=..' "$ENV_FILE"; then
  c_ok "$ENV_FILE present with a key — reusing it (keeps existing encrypted data)"
else
  DOMAIN="${DOMAIN:-}"
  if [ -z "$DOMAIN" ]; then
    read -rp "  Public domain for this DAM (e.g. dam.example.com): " DOMAIN
  fi
  [ -n "$DOMAIN" ] || die "a domain is required (Caddy provisions TLS for it)"
  gen(){ openssl rand -hex "$1"; }
  cat > "$ENV_FILE" <<EOF
# Generated by install.sh on $(date -u +%FT%TZ). KEEP THIS FILE SAFE.
# CREDENTIAL_ENCRYPTION_KEY protects every stored connector credential/secret —
# losing it makes them UNRECOVERABLE. Back it up out-of-band.
CREDENTIAL_ENCRYPTION_KEY=$(gen 32)
DAM_JWT_SECRET=$(gen 32)
DAM_PG_PASSWORD=$(gen 16)
DAM_CLICKHOUSE_PASSWORD=$(gen 16)
APP_BASE_URL=https://${DOMAIN}
API_PUBLIC_URL=https://${DOMAIN}
PUBLIC_CONTROL_PLANE=${DOMAIN}
# Optional (SSO / SMTP / KMS / payments) — leave blank if unused:
AZURE_CLIENT_ID=
AZURE_TENANT_ID=
AZURE_CLIENT_SECRET=
AZURE_REDIRECT_URI=
EOF
  chmod 600 "$ENV_FILE"
  c_ok "generated $ENV_FILE (fresh secrets, domain=$DOMAIN, chmod 600)"
  c_warn "BACK UP $ENV_FILE — the encryption key cannot be recovered."
fi

# ── 5. bring the stack up ───────────────────────────────────────────────────
step "5 · start the stack"
docker compose -f "$COMPOSE" --env-file "$ENV_FILE" up -d
c_ok "compose up issued"

# ── 6. wait for health + verify ─────────────────────────────────────────────
step "6 · verify"
printf "  waiting for dam-api"
for i in $(seq 1 40); do
  code=$(docker exec dam-api sh -c 'wget -qO- --server-response http://localhost:3000/api/auth/login 2>&1 | grep -o "HTTP/1.1 [0-9]*" | grep -o "[0-9]*$"' 2>/dev/null | head -1 || true)
  [ "$code" = "400" ] || [ "$code" = "401" ] && { printf " up\n"; break; }
  printf "."; sleep 3
done
UP=$(docker compose -f "$COMPOSE" ps --services --status running 2>/dev/null | wc -l)
c_ok "$UP services running"
docker exec dam-postgres sh -lc 'pg_isready -U dam_admin -d dam_control' >/dev/null 2>&1 && c_ok "postgres ready" || c_warn "postgres not ready yet"

DOM=$(grep -m1 '^PUBLIC_CONTROL_PLANE=' "$ENV_FILE" | cut -d= -f2)
cat <<DONE

$(printf '\033[1m== SecurEra DAM is up ==\033[0m')
  Next:
    1. Point DNS  ${DOM:-<your-domain>}  →  this host's public IP (a static/reserved IP).
    2. Open inbound 80 + 443 in the firewall/security-group (Caddy provisions TLS on first hit).
    3. Browse to  https://${DOM:-<your-domain>}  — Caddy issues the cert automatically.
    4. Provision the first admin (out-of-band — no default credentials are seeded).
  Manage:  docker compose -f $COMPOSE ps   |   ... logs -f dam-api   |   ... down
DONE
