// VA check library — CIS-derived database security checks (data, not code).
//
// Each record is a read-only query + an expected result. Config checks (SHOW VARIABLES / SHOW)
// run with any login; privilege/account checks read catalog tables (mysql.user, pg_roles) and
// degrade to status "error" where the reader lacks access. Titles/sections/refs map each finding
// to its CIS benchmark section and adjacent framework controls so they roll into Compliance.
package main

// ── MySQL / MariaDB (CIS MySQL 8.0 Benchmark) ────────────────────────────────
var mysqlVaChecks = []vaCheck{
	// Configuration hardening
	{ID: "mysql-local-infile", Section: "4.3", Title: "'local_infile' is disabled", Severity: "high",
		Query: "SHOW VARIABLES LIKE 'local_infile'", Expect: vaExpect{Op: "equals", Column: "Value", Value: "OFF"},
		Remediation: "SET GLOBAL local_infile=0; and set local_infile=OFF in my.cnf — prevents client-side file reads via LOAD DATA LOCAL.",
		Refs: []string{"CIS MySQL 8.0 §4.3", "PCI-DSS 2.2.5"}},
	{ID: "mysql-require-secure-transport", Section: "6.5", Title: "Connections require TLS (require_secure_transport)", Severity: "high",
		Query: "SHOW VARIABLES LIKE 'require_secure_transport'", Expect: vaExpect{Op: "equals", Column: "Value", Value: "ON"},
		Remediation: "SET PERSIST require_secure_transport=ON; — rejects unencrypted client connections.",
		Refs: []string{"CIS MySQL 8.0 §6.5", "PCI-DSS 4.1"}},
	{ID: "mysql-have-ssl", Section: "6.1", Title: "TLS/SSL is available on the server", Severity: "medium",
		Query: "SHOW VARIABLES LIKE 'have_ssl'", Expect: vaExpect{Op: "equals", Column: "Value", Value: "YES"},
		Remediation: "Configure ssl_cert/ssl_key/ssl_ca so the server can negotiate TLS.",
		Refs: []string{"CIS MySQL 8.0 §6.1", "PCI-DSS 4.1"}},
	{ID: "mysql-tls-version", Section: "6.6", Title: "Deprecated TLSv1/TLSv1.1 not offered", Severity: "medium",
		Query: "SHOW VARIABLES LIKE 'tls_version'", Expect: vaExpect{Op: "notContains", Column: "Value", Value: "TLSv1.1"},
		Remediation: "SET PERSIST tls_version='TLSv1.2,TLSv1.3'; — drop the deprecated protocols.",
		Refs: []string{"CIS MySQL 8.0 §6.6"}},
	{ID: "mysql-log-error", Section: "6.2", Title: "Error log is configured", Severity: "low",
		Query: "SHOW VARIABLES LIKE 'log_error'", Expect: vaExpect{Op: "notEmpty", Column: "Value"},
		Remediation: "Set log_error to a file so startup/security errors are retained.",
		Refs: []string{"CIS MySQL 8.0 §6.2"}},
	{ID: "mysql-log-bin-trust", Section: "7.x", Title: "log_bin_trust_function_creators is OFF", Severity: "medium",
		Query: "SHOW VARIABLES LIKE 'log_bin_trust_function_creators'", Expect: vaExpect{Op: "equals", Column: "Value", Value: "OFF"},
		Remediation: "SET PERSIST log_bin_trust_function_creators=0; — avoids unsafe stored-function replication.",
		Refs: []string{"CIS MySQL 8.0 §7"}},
	{ID: "mysql-sql-mode-strict", Section: "9.x", Title: "sql_mode enforces STRICT", Severity: "low",
		Query: "SHOW VARIABLES LIKE 'sql_mode'", Expect: vaExpect{Op: "contains", Column: "Value", Value: "STRICT"},
		Remediation: "Include STRICT_ALL_TABLES (or STRICT_TRANS_TABLES) in sql_mode.",
		Refs: []string{"CIS MySQL 8.0 §9"}},
	{ID: "mysql-skip-name-resolve", Section: "5.x", Title: "skip_name_resolve is ON", Severity: "low",
		Query: "SHOW VARIABLES LIKE 'skip_name_resolve'", Expect: vaExpect{Op: "equals", Column: "Value", Value: "ON"},
		Remediation: "SET skip_name_resolve=ON in my.cnf — host grants use IPs, not spoofable DNS.",
		Refs: []string{"CIS MySQL 8.0 §5"}},
	{ID: "mysql-password-lifetime", Section: "5.3", Title: "A default password lifetime is set", Severity: "low",
		Query: "SHOW VARIABLES LIKE 'default_password_lifetime'", Expect: vaExpect{Op: "notEquals", Column: "Value", Value: "0"},
		Remediation: "SET PERSIST default_password_lifetime=90; — 0 means passwords never expire.",
		Refs: []string{"CIS MySQL 8.0 §5.3", "PCI-DSS 8.3.9"}},
	{ID: "mysql-validate-password", Section: "5.2", Title: "Password-strength validation is active", Severity: "medium",
		Query: "SELECT plugin_status FROM information_schema.plugins WHERE plugin_name LIKE 'validate_password%' AND plugin_status='ACTIVE'",
		Expect:      vaExpect{Op: "rowsNonZero"},
		Remediation: "INSTALL COMPONENT 'file://component_validate_password'; — enforce password complexity.",
		Refs:        []string{"CIS MySQL 8.0 §5.2", "PCI-DSS 8.3.6"}},

	// Accounts & privileges (read mysql.user — may need an elevated reader)
	{ID: "mysql-empty-passwords", Section: "4.1", Title: "No accounts with an empty password", Severity: "critical",
		Query: "SELECT user, host FROM mysql.user WHERE (authentication_string='' OR authentication_string IS NULL) AND plugin IN ('mysql_native_password','caching_sha2_password','')",
		Expect:      vaExpect{Op: "rowsZero"},
		Remediation: "ALTER USER '<u>'@'<h>' IDENTIFIED BY '<strong-password>'; or drop the account.",
		Refs:        []string{"CIS MySQL 8.0 §4.1", "PCI-DSS 8.3.1"}},
	{ID: "mysql-anonymous-accounts", Section: "4.2", Title: "No anonymous accounts", Severity: "high",
		Query: "SELECT user, host FROM mysql.user WHERE user=''", Expect: vaExpect{Op: "rowsZero"},
		Remediation: "DROP USER ''@'<host>'; — anonymous logins bypass user accountability.",
		Refs: []string{"CIS MySQL 8.0 §4.2"}},
	{ID: "mysql-wildcard-host", Section: "4.x", Title: "No accounts granted from any host ('%')", Severity: "medium",
		Query: "SELECT user, host FROM mysql.user WHERE host='%'", Expect: vaExpect{Op: "rowsZero"},
		Remediation: "Recreate the account scoped to specific hosts/subnets instead of '%'.",
		Refs: []string{"CIS MySQL 8.0 §4"}},
	{ID: "mysql-super-priv", Section: "8.x", Title: "SUPER privilege limited to admin accounts", Severity: "high",
		Query: "SELECT user, host FROM mysql.user WHERE Super_priv='Y' AND user NOT IN ('root','mysql.sys','mysql.session','mysql.infoschema')",
		Expect:      vaExpect{Op: "rowsZero"},
		Remediation: "REVOKE SUPER ON *.* FROM '<u>'@'<h>'; — grant only the specific dynamic privileges needed.",
		Refs:        []string{"CIS MySQL 8.0 §8", "PCI-DSS 7.2"}},
	{ID: "mysql-file-priv", Section: "8.x", Title: "FILE privilege limited to admin accounts", Severity: "high",
		Query: "SELECT user, host FROM mysql.user WHERE File_priv='Y' AND user NOT IN ('root','mysql.infoschema','mysql.sys','mysql.session')",
		Expect:      vaExpect{Op: "rowsZero"},
		Remediation: "REVOKE FILE ON *.* FROM '<u>'@'<h>'; — FILE allows server-side file read/write.",
		Refs:        []string{"CIS MySQL 8.0 §8"}},
	{ID: "mysql-grant-option", Section: "8.x", Title: "GRANT OPTION not held broadly", Severity: "medium",
		Query: "SELECT user, host FROM mysql.user WHERE Grant_priv='Y' AND user NOT IN ('root','mysql.sys','mysql.session','mysql.infoschema')",
		Expect:      vaExpect{Op: "rowsZero"},
		Remediation: "REVOKE GRANT OPTION ON *.* FROM '<u>'@'<h>'; — limits privilege propagation.",
		Refs:        []string{"CIS MySQL 8.0 §8", "PCI-DSS 7.2"}},
	{ID: "mysql-global-select", Section: "8.x", Title: "No non-admin account has global SELECT", Severity: "medium",
		Query: "SELECT user, host FROM mysql.user WHERE Select_priv='Y' AND user NOT IN ('root','mysql.sys','mysql.session','mysql.infoschema')",
		Expect:      vaExpect{Op: "rowsZero"},
		Remediation: "Grant SELECT per-schema (GRANT SELECT ON app.* ...) instead of globally.",
		Refs:        []string{"CIS MySQL 8.0 §8", "PCI-DSS 7.2"}},
	{ID: "mysql-process-priv", Section: "8.x", Title: "PROCESS privilege limited", Severity: "low",
		Query: "SELECT user, host FROM mysql.user WHERE Process_priv='Y' AND user NOT IN ('root','mysql.sys','mysql.session','mysql.infoschema')",
		Expect:      vaExpect{Op: "rowsZero"},
		Remediation: "REVOKE PROCESS ON *.* FROM '<u>'@'<h>'; — PROCESS exposes other sessions' queries.",
		Refs:        []string{"CIS MySQL 8.0 §8"}},
}

// ── PostgreSQL (CIS PostgreSQL Benchmark) ────────────────────────────────────
var postgresVaChecks = []vaCheck{
	// Connection & TLS
	{ID: "pg-ssl-on", Section: "6.8", Title: "TLS/SSL is enabled", Severity: "high",
		Query: "SHOW ssl", Expect: vaExpect{Op: "equals", Value: "on"},
		Remediation: "Set ssl=on with server cert/key in postgresql.conf and require TLS in pg_hba.conf.",
		Refs: []string{"CIS PostgreSQL §6.8", "PCI-DSS 4.1"}},
	{ID: "pg-password-encryption", Section: "5.x", Title: "Passwords use SCRAM-SHA-256 (not md5)", Severity: "high",
		Query: "SHOW password_encryption", Expect: vaExpect{Op: "equals", Value: "scram-sha-256"},
		Remediation: "Set password_encryption='scram-sha-256' and re-set role passwords; md5 is weak.",
		Refs: []string{"CIS PostgreSQL §5", "PCI-DSS 8.3.2"}},
	{ID: "pg-ssl-min-proto", Section: "6.x", Title: "Minimum TLS protocol is TLSv1.2+", Severity: "medium",
		Query: "SHOW ssl_min_protocol_version", Expect: vaExpect{Op: "notContains", Value: "TLSv1.1"},
		Remediation: "Set ssl_min_protocol_version='TLSv1.2' (or higher).",
		Refs: []string{"CIS PostgreSQL §6"}},

	// Logging / audit
	{ID: "pg-logging-collector", Section: "3.1.2", Title: "Logging collector is enabled", Severity: "low",
		Query: "SHOW logging_collector", Expect: vaExpect{Op: "equals", Value: "on"},
		Remediation: "Set logging_collector=on so server logs are captured to files.",
		Refs: []string{"CIS PostgreSQL §3.1.2"}},
	{ID: "pg-log-connections", Section: "3.1.x", Title: "Connections are logged", Severity: "low",
		Query: "SHOW log_connections", Expect: vaExpect{Op: "equals", Value: "on"},
		Remediation: "Set log_connections=on for authentication accountability.",
		Refs: []string{"CIS PostgreSQL §3.1", "PCI-DSS 10.2"}},
	{ID: "pg-log-disconnections", Section: "3.1.x", Title: "Disconnections are logged", Severity: "low",
		Query: "SHOW log_disconnections", Expect: vaExpect{Op: "equals", Value: "on"},
		Remediation: "Set log_disconnections=on to record session end + duration.",
		Refs: []string{"CIS PostgreSQL §3.1", "PCI-DSS 10.2"}},
	{ID: "pg-log-statement", Section: "3.1.x", Title: "Statement logging is not disabled", Severity: "medium",
		Query: "SHOW log_statement", Expect: vaExpect{Op: "notEquals", Value: "none"},
		Remediation: "Set log_statement='ddl' (or 'mod'/'all') to record schema/data changes.",
		Refs: []string{"CIS PostgreSQL §3.1", "PCI-DSS 10.2"}},
	{ID: "pg-pgaudit", Section: "3.2", Title: "pgAudit extension is installed", Severity: "medium",
		Query: "SELECT extname FROM pg_extension WHERE extname='pgaudit'", Expect: vaExpect{Op: "rowsNonZero"},
		Remediation: "Install pgaudit (shared_preload_libraries + CREATE EXTENSION) for detailed audit logging.",
		Refs: []string{"CIS PostgreSQL §3.2", "PCI-DSS 10.2"}},

	// Accounts & privileges
	{ID: "pg-superusers", Section: "4.x", Title: "Superuser role limited to 'postgres'", Severity: "high",
		Query: "SELECT rolname FROM pg_roles WHERE rolsuper AND rolname <> 'postgres' AND rolname NOT LIKE 'pg_%'",
		Expect:      vaExpect{Op: "rowsZero"},
		Remediation: "ALTER ROLE <r> NOSUPERUSER; — grant specific privileges instead of superuser.",
		Refs:        []string{"CIS PostgreSQL §4", "PCI-DSS 7.2"}},
	{ID: "pg-createrole", Section: "4.x", Title: "CREATEROLE limited to admins", Severity: "medium",
		Query: "SELECT rolname FROM pg_roles WHERE rolcreaterole AND rolname <> 'postgres' AND rolname NOT LIKE 'pg_%'",
		Expect:      vaExpect{Op: "rowsZero"},
		Remediation: "ALTER ROLE <r> NOCREATEROLE; — CREATEROLE can escalate to other roles.",
		Refs:        []string{"CIS PostgreSQL §4"}},
	{ID: "pg-public-db-create", Section: "4.x", Title: "PUBLIC lacks CREATE on the database", Severity: "medium",
		Query: "SELECT has_database_privilege('public', current_database(), 'CREATE') AS v", Expect: vaExpect{Op: "equals", Column: "v", Value: "false"},
		Remediation: "REVOKE CREATE ON DATABASE <db> FROM PUBLIC; — stops any role creating schemas.",
		Refs: []string{"CIS PostgreSQL §4", "PCI-DSS 7.2"}},
	{ID: "pg-public-schema-create", Section: "4.x", Title: "PUBLIC lacks CREATE on the public schema", Severity: "medium",
		Query: "SELECT has_schema_privilege('public', 'public', 'CREATE') AS v", Expect: vaExpect{Op: "equals", Column: "v", Value: "false"},
		Remediation: "REVOKE CREATE ON SCHEMA public FROM PUBLIC; — prevents object creation by any role.",
		Refs: []string{"CIS PostgreSQL §4"}},
	{ID: "pg-hba-no-trust", Section: "6.7", Title: "No 'trust' authentication in pg_hba", Severity: "critical",
		Query: "SELECT type, database::text, user_name::text FROM pg_hba_file_rules WHERE auth_method='trust'",
		Expect:      vaExpect{Op: "rowsZero"},
		Remediation: "Replace 'trust' rules in pg_hba.conf with scram-sha-256; trust allows passwordless login.",
		Refs:        []string{"CIS PostgreSQL §6.7", "PCI-DSS 8.3.1"}},
	{ID: "pg-login-no-expiry", Section: "4.x", Title: "Login roles have a password expiry set", Severity: "low",
		Query: "SELECT rolname FROM pg_roles WHERE rolcanlogin AND rolvaliduntil IS NULL AND rolname NOT LIKE 'pg_%' AND rolname <> 'postgres'",
		Expect:      vaExpect{Op: "rowsZero"},
		Remediation: "ALTER ROLE <r> VALID UNTIL '<date>'; — set a credential expiry for login roles.",
		Refs:        []string{"CIS PostgreSQL §4", "PCI-DSS 8.3.9"}},

	// Integrity
	{ID: "pg-fsync", Section: "x", Title: "fsync is enabled (crash-safe writes)", Severity: "low",
		Query: "SHOW fsync", Expect: vaExpect{Op: "equals", Value: "on"},
		Remediation: "Set fsync=on — disabling it risks data loss/corruption on crash.",
		Refs: []string{"CIS PostgreSQL"}},
}
