// VA check library — CIS-derived database security checks (data, not code).
//
// Each record is a read-only query + an expected result. Config checks (SHOW VARIABLES / SHOW)
// run with any login; privilege/account checks read catalog tables (mysql.user, pg_roles) and
// degrade to status "error" where the reader lacks access. Titles/sections/refs map each finding
// to its CIS benchmark section and adjacent framework controls so they roll into Compliance.
package main

// ── MySQL / MariaDB (CIS MySQL 8.0 Benchmark) ────────────────────────────────
var mysqlVaChecks = []vaCheck{
	// Configuration hardening
	{ID: "mysql-local-infile", Section: "4.3", Title: "'local_infile' is disabled", Severity: "high",
		Query: "SHOW VARIABLES LIKE 'local_infile'", Expect: vaExpect{Op: "equals", Column: "Value", Value: "OFF"},
		Remediation: "SET GLOBAL local_infile=0; and set local_infile=OFF in my.cnf — prevents client-side file reads via LOAD DATA LOCAL.",
		Refs: []string{"CIS MySQL 8.0 §4.3", "PCI-DSS 2.2.5"}},
	{ID: "mysql-require-secure-transport", Section: "6.5", Title: "Connections require TLS (require_secure_transport)", Severity: "high",
		Query: "SHOW VARIABLES LIKE 'require_secure_transport'", Expect: vaExpect{Op: "equals", Column: "Value", Value: "ON"},
		Remediation: "SET PERSIST require_secure_transport=ON; — rejects unencrypted client connections.",
		Refs: []string{"CIS MySQL 8.0 §6.5", "PCI-DSS 4.1"}},
	{ID: "mysql-have-ssl", Section: "6.1", Title: "TLS/SSL is available on the server", Severity: "medium",
		Query: "SHOW VARIABLES LIKE 'have_ssl'", Expect: vaExpect{Op: "equals", Column: "Value", Value: "YES"},
		Remediation: "Configure ssl_cert/ssl_key/ssl_ca so the server can negotiate TLS.",
		Refs: []string{"CIS MySQL 8.0 §6.1", "PCI-DSS 4.1"}},
	{ID: "mysql-tls-version", Section: "6.6", Title: "Deprecated TLSv1/TLSv1.1 not offered", Severity: "medium",
		Query: "SHOW VARIABLES LIKE 'tls_version'", Expect: vaExpect{Op: "notContains", Column: "Value", Value: "TLSv1.1"},
		Remediation: "SET PERSIST tls_version='TLSv1.2,TLSv1.3'; — drop the deprecated protocols.",
		Refs: []string{"CIS MySQL 8.0 §6.6"}},
	{ID: "mysql-log-error", Section: "6.2", Title: "Error log is configured", Severity: "low",
		Query: "SHOW VARIABLES LIKE 'log_error'", Expect: vaExpect{Op: "notEmpty", Column: "Value"},
		Remediation: "Set log_error to a file so startup/security errors are retained.",
		Refs: []string{"CIS MySQL 8.0 §6.2"}},
	{ID: "mysql-log-bin-trust", Section: "7.x", Title: "log_bin_trust_function_creators is OFF", Severity: "medium",
		Query: "SHOW VARIABLES LIKE 'log_bin_trust_function_creators'", Expect: vaExpect{Op: "equals", Column: "Value", Value: "OFF"},
		Remediation: "SET PERSIST log_bin_trust_function_creators=0; — avoids unsafe stored-function replication.",
		Refs: []string{"CIS MySQL 8.0 §7"}},
	{ID: "mysql-sql-mode-strict", Section: "9.x", Title: "sql_mode enforces STRICT", Severity: "low",
		Query: "SHOW VARIABLES LIKE 'sql_mode'", Expect: vaExpect{Op: "contains", Column: "Value", Value: "STRICT"},
		Remediation: "Include STRICT_ALL_TABLES (or STRICT_TRANS_TABLES) in sql_mode.",
		Refs: []string{"CIS MySQL 8.0 §9"}},
	{ID: "mysql-skip-name-resolve", Section: "5.x", Title: "skip_name_resolve is ON", Severity: "low",
		Query: "SHOW VARIABLES LIKE 'skip_name_resolve'", Expect: vaExpect{Op: "equals", Column: "Value", Value: "ON"},
		Remediation: "SET skip_name_resolve=ON in my.cnf — host grants use IPs, not spoofable DNS.",
		Refs: []string{"CIS MySQL 8.0 §5"}},
	{ID: "mysql-password-lifetime", Section: "5.3", Title: "A default password lifetime is set", Severity: "low",
		Query: "SHOW VARIABLES LIKE 'default_password_lifetime'", Expect: vaExpect{Op: "notEquals", Column: "Value", Value: "0"},
		Remediation: "SET PERSIST default_password_lifetime=90; — 0 means passwords never expire.",
		Refs: []string{"CIS MySQL 8.0 §5.3", "PCI-DSS 8.3.9"}},
	{ID: "mysql-validate-password", Section: "5.2", Title: "Password-strength validation is active", Severity: "medium",
		Query: "SELECT plugin_status FROM information_schema.plugins WHERE plugin_name LIKE 'validate_password%' AND plugin_status='ACTIVE'",
		Expect:      vaExpect{Op: "rowsNonZero"},
		Remediation: "INSTALL COMPONENT 'file://component_validate_password'; — enforce password complexity.",
		Refs:        []string{"CIS MySQL 8.0 §5.2", "PCI-DSS 8.3.6"}},

	// Accounts & privileges (read mysql.user — may need an elevated reader)
	{ID: "mysql-empty-passwords", Section: "4.1", Title: "No accounts with an empty password", Severity: "critical",
		Query: "SELECT user, host FROM mysql.user WHERE (authentication_string='' OR authentication_string IS NULL) AND plugin IN ('mysql_native_password','caching_sha2_password','')",
		Expect:      vaExpect{Op: "rowsZero"},
		Remediation: "ALTER USER '<u>'@'<h>' IDENTIFIED BY '<strong-password>'; or drop the account.",
		Refs:        []string{"CIS MySQL 8.0 §4.1", "PCI-DSS 8.3.1"}},
	{ID: "mysql-anonymous-accounts", Section: "4.2", Title: "No anonymous accounts", Severity: "high",
		Query: "SELECT user, host FROM mysql.user WHERE user=''", Expect: vaExpect{Op: "rowsZero"},
		Remediation: "DROP USER ''@'<host>'; — anonymous logins bypass user accountability.",
		Refs: []string{"CIS MySQL 8.0 §4.2"}},
	{ID: "mysql-wildcard-host", Section: "4.x", Title: "No accounts granted from any host ('%')", Severity: "medium",
		Query: "SELECT user, host FROM mysql.user WHERE host='%'", Expect: vaExpect{Op: "rowsZero"},
		Remediation: "Recreate the account scoped to specific hosts/subnets instead of '%'.",
		Refs: []string{"CIS MySQL 8.0 §4"}},
	{ID: "mysql-super-priv", Section: "8.x", Title: "SUPER privilege limited to admin accounts", Severity: "high",
		Query: "SELECT user, host FROM mysql.user WHERE Super_priv='Y' AND user NOT IN ('root','mysql.sys','mysql.session','mysql.infoschema')",
		Expect:      vaExpect{Op: "rowsZero"},
		Remediation: "REVOKE SUPER ON *.* FROM '<u>'@'<h>'; — grant only the specific dynamic privileges needed.",
		Refs:        []string{"CIS MySQL 8.0 §8", "PCI-DSS 7.2"}},
	{ID: "mysql-file-priv", Section: "8.x", Title: "FILE privilege limited to admin accounts", Severity: "high",
		Query: "SELECT user, host FROM mysql.user WHERE File_priv='Y' AND user NOT IN ('root','mysql.infoschema','mysql.sys','mysql.session')",
		Expect:      vaExpect{Op: "rowsZero"},
		Remediation: "REVOKE FILE ON *.* FROM '<u>'@'<h>'; — FILE allows server-side file read/write.",
		Refs:        []string{"CIS MySQL 8.0 §8"}},
	{ID: "mysql-grant-option", Section: "8.x", Title: "GRANT OPTION not held broadly", Severity: "medium",
		Query: "SELECT user, host FROM mysql.user WHERE Grant_priv='Y' AND user NOT IN ('root','mysql.sys','mysql.session','mysql.infoschema')",
		Expect:      vaExpect{Op: "rowsZero"},
		Remediation: "REVOKE GRANT OPTION ON *.* FROM '<u>'@'<h>'; — limits privilege propagation.",
		Refs:        []string{"CIS MySQL 8.0 §8", "PCI-DSS 7.2"}},
	{ID: "mysql-global-select", Section: "8.x", Title: "No non-admin account has global SELECT", Severity: "medium",
		Query: "SELECT user, host FROM mysql.user WHERE Select_priv='Y' AND user NOT IN ('root','mysql.sys','mysql.session','mysql.infoschema')",
		Expect:      vaExpect{Op: "rowsZero"},
		Remediation: "Grant SELECT per-schema (GRANT SELECT ON app.* ...) instead of globally.",
		Refs:        []string{"CIS MySQL 8.0 §8", "PCI-DSS 7.2"}},
	{ID: "mysql-process-priv", Section: "8.x", Title: "PROCESS privilege limited", Severity: "low",
		Query: "SELECT user, host FROM mysql.user WHERE Process_priv='Y' AND user NOT IN ('root','mysql.sys','mysql.session','mysql.infoschema')",
		Expect:      vaExpect{Op: "rowsZero"},
		Remediation: "REVOKE PROCESS ON *.* FROM '<u>'@'<h>'; — PROCESS exposes other sessions' queries.",
		Refs:        []string{"CIS MySQL 8.0 §8"}},
}

// ── PostgreSQL (CIS PostgreSQL Benchmark) ────────────────────────────────────
var postgresVaChecks = []vaCheck{
	// Connection & TLS
	{ID: "pg-ssl-on", Section: "6.8", Title: "TLS/SSL is enabled", Severity: "high",
		Query: "SHOW ssl", Expect: vaExpect{Op: "equals", Value: "on"},
		Remediation: "Set ssl=on with server cert/key in postgresql.conf and require TLS in pg_hba.conf.",
		Refs: []string{"CIS PostgreSQL §6.8", "PCI-DSS 4.1"}},
	{ID: "pg-password-encryption", Section: "5.x", Title: "Passwords use SCRAM-SHA-256 (not md5)", Severity: "high",
		Query: "SHOW password_encryption", Expect: vaExpect{Op: "equals", Value: "scram-sha-256"},
		Remediation: "Set password_encryption='scram-sha-256' and re-set role passwords; md5 is weak.",
		Refs: []string{"CIS PostgreSQL §5", "PCI-DSS 8.3.2"}},
	{ID: "pg-ssl-min-proto", Section: "6.x", Title: "Minimum TLS protocol is TLSv1.2+", Severity: "medium",
		Query: "SHOW ssl_min_protocol_version", Expect: vaExpect{Op: "notContains", Value: "TLSv1.1"},
		Remediation: "Set ssl_min_protocol_version='TLSv1.2' (or higher).",
		Refs: []string{"CIS PostgreSQL §6"}},

	// Logging / audit
	{ID: "pg-logging-collector", Section: "3.1.2", Title: "Logging collector is enabled", Severity: "low",
		Query: "SHOW logging_collector", Expect: vaExpect{Op: "equals", Value: "on"},
		Remediation: "Set logging_collector=on so server logs are captured to files.",
		Refs: []string{"CIS PostgreSQL §3.1.2"}},
	{ID: "pg-log-connections", Section: "3.1.x", Title: "Connections are logged", Severity: "low",
		Query: "SHOW log_connections", Expect: vaExpect{Op: "equals", Value: "on"},
		Remediation: "Set log_connections=on for authentication accountability.",
		Refs: []string{"CIS PostgreSQL §3.1", "PCI-DSS 10.2"}},
	{ID: "pg-log-disconnections", Section: "3.1.x", Title: "Disconnections are logged", Severity: "low",
		Query: "SHOW log_disconnections", Expect: vaExpect{Op: "equals", Value: "on"},
		Remediation: "Set log_disconnections=on to record session end + duration.",
		Refs: []string{"CIS PostgreSQL §3.1", "PCI-DSS 10.2"}},
	{ID: "pg-log-statement", Section: "3.1.x", Title: "Statement logging is not disabled", Severity: "medium",
		Query: "SHOW log_statement", Expect: vaExpect{Op: "notEquals", Value: "none"},
		Remediation: "Set log_statement='ddl' (or 'mod'/'all') to record schema/data changes.",
		Refs: []string{"CIS PostgreSQL §3.1", "PCI-DSS 10.2"}},
	{ID: "pg-pgaudit", Section: "3.2", Title: "pgAudit extension is installed", Severity: "medium",
		Query: "SELECT extname FROM pg_extension WHERE extname='pgaudit'", Expect: vaExpect{Op: "rowsNonZero"},
		Remediation: "Install pgaudit (shared_preload_libraries + CREATE EXTENSION) for detailed audit logging.",
		Refs: []string{"CIS PostgreSQL §3.2", "PCI-DSS 10.2"}},

	// Accounts & privileges
	{ID: "pg-superusers", Section: "4.x", Title: "Superuser role limited to 'postgres'", Severity: "high",
		Query: "SELECT rolname FROM pg_roles WHERE rolsuper AND rolname <> 'postgres' AND rolname NOT LIKE 'pg_%'",
		Expect:      vaExpect{Op: "rowsZero"},
		Remediation: "ALTER ROLE <r> NOSUPERUSER; — grant specific privileges instead of superuser.",
		Refs:        []string{"CIS PostgreSQL §4", "PCI-DSS 7.2"}},
	{ID: "pg-createrole", Section: "4.x", Title: "CREATEROLE limited to admins", Severity: "medium",
		Query: "SELECT rolname FROM pg_roles WHERE rolcreaterole AND rolname <> 'postgres' AND rolname NOT LIKE 'pg_%'",
		Expect:      vaExpect{Op: "rowsZero"},
		Remediation: "ALTER ROLE <r> NOCREATEROLE; — CREATEROLE can escalate to other roles.",
		Refs:        []string{"CIS PostgreSQL §4"}},
	{ID: "pg-public-db-create", Section: "4.x", Title: "PUBLIC lacks CREATE on the database", Severity: "medium",
		Query: "SELECT has_database_privilege('public', current_database(), 'CREATE') AS v", Expect: vaExpect{Op: "equals", Column: "v", Value: "false"},
		Remediation: "REVOKE CREATE ON DATABASE <db> FROM PUBLIC; — stops any role creating schemas.",
		Refs: []string{"CIS PostgreSQL §4", "PCI-DSS 7.2"}},
	{ID: "pg-public-schema-create", Section: "4.x", Title: "PUBLIC lacks CREATE on the public schema", Severity: "medium",
		Query: "SELECT has_schema_privilege('public', 'public', 'CREATE') AS v", Expect: vaExpect{Op: "equals", Column: "v", Value: "false"},
		Remediation: "REVOKE CREATE ON SCHEMA public FROM PUBLIC; — prevents object creation by any role.",
		Refs: []string{"CIS PostgreSQL §4"}},
	{ID: "pg-hba-no-trust", Section: "6.7", Title: "No 'trust' authentication in pg_hba", Severity: "critical",
		Query: "SELECT type, database::text, user_name::text FROM pg_hba_file_rules WHERE auth_method='trust'",
		Expect:      vaExpect{Op: "rowsZero"},
		Remediation: "Replace 'trust' rules in pg_hba.conf with scram-sha-256; trust allows passwordless login.",
		Refs:        []string{"CIS PostgreSQL §6.7", "PCI-DSS 8.3.1"}},
	{ID: "pg-login-no-expiry", Section: "4.x", Title: "Login roles have a password expiry set", Severity: "low",
		Query: "SELECT rolname FROM pg_roles WHERE rolcanlogin AND rolvaliduntil IS NULL AND rolname NOT LIKE 'pg_%' AND rolname <> 'postgres'",
		Expect:      vaExpect{Op: "rowsZero"},
		Remediation: "ALTER ROLE <r> VALID UNTIL '<date>'; — set a credential expiry for login roles.",
		Refs:        []string{"CIS PostgreSQL §4", "PCI-DSS 8.3.9"}},

	// Integrity
	{ID: "pg-fsync", Section: "x", Title: "fsync is enabled (crash-safe writes)", Severity: "low",
		Query: "SHOW fsync", Expect: vaExpect{Op: "equals", Value: "on"},
		Remediation: "Set fsync=on — disabling it risks data loss/corruption on crash.",
		Refs: []string{"CIS PostgreSQL"}},
}

// ── Microsoft SQL Server (CIS SQL Server Benchmark) ──────────────────────────
// Config checks read sys.configurations (readable by public); login/role checks read
// sys.sql_logins / sys.server_principals and degrade to "error" without VIEW ANY DEFINITION.
var mssqlVaChecks = []vaCheck{
	{ID: "mssql-xp-cmdshell", Section: "2.1", Title: "'xp_cmdshell' is disabled", Severity: "critical",
		Query: "SELECT CAST(value_in_use AS INT) v FROM sys.configurations WHERE name='xp_cmdshell'", Expect: vaExpect{Op: "equals", Column: "v", Value: "0"},
		Remediation: "EXEC sp_configure 'xp_cmdshell',0; RECONFIGURE; — xp_cmdshell runs OS commands.",
		Refs: []string{"CIS SQL Server §2.1", "PCI-DSS 2.2.5"}},
	{ID: "mssql-ole-automation", Section: "2.2", Title: "'Ole Automation Procedures' is disabled", Severity: "high",
		Query: "SELECT CAST(value_in_use AS INT) v FROM sys.configurations WHERE name='Ole Automation Procedures'", Expect: vaExpect{Op: "equals", Column: "v", Value: "0"},
		Remediation: "EXEC sp_configure 'Ole Automation Procedures',0; RECONFIGURE;",
		Refs: []string{"CIS SQL Server §2.2"}},
	{ID: "mssql-adhoc-queries", Section: "2.3", Title: "'Ad Hoc Distributed Queries' is disabled", Severity: "medium",
		Query: "SELECT CAST(value_in_use AS INT) v FROM sys.configurations WHERE name='Ad Hoc Distributed Queries'", Expect: vaExpect{Op: "equals", Column: "v", Value: "0"},
		Remediation: "EXEC sp_configure 'Ad Hoc Distributed Queries',0; RECONFIGURE;",
		Refs: []string{"CIS SQL Server §2.3"}},
	{ID: "mssql-clr-enabled", Section: "2.4", Title: "'clr enabled' is disabled", Severity: "medium",
		Query: "SELECT CAST(value_in_use AS INT) v FROM sys.configurations WHERE name='clr enabled'", Expect: vaExpect{Op: "equals", Column: "v", Value: "0"},
		Remediation: "EXEC sp_configure 'clr enabled',0; RECONFIGURE; (unless CLR assemblies are required).",
		Refs: []string{"CIS SQL Server §2.4"}},
	{ID: "mssql-cross-db-ownership", Section: "2.5", Title: "'cross db ownership chaining' is disabled", Severity: "medium",
		Query: "SELECT CAST(value_in_use AS INT) v FROM sys.configurations WHERE name='cross db ownership chaining'", Expect: vaExpect{Op: "equals", Column: "v", Value: "0"},
		Remediation: "EXEC sp_configure 'cross db ownership chaining',0; RECONFIGURE;",
		Refs: []string{"CIS SQL Server §2.5"}},
	{ID: "mssql-scan-startup", Section: "2.6", Title: "'scan for startup procs' is disabled", Severity: "medium",
		Query: "SELECT CAST(value_in_use AS INT) v FROM sys.configurations WHERE name='scan for startup procs'", Expect: vaExpect{Op: "equals", Column: "v", Value: "0"},
		Remediation: "EXEC sp_configure 'scan for startup procs',0; RECONFIGURE;",
		Refs: []string{"CIS SQL Server §2.6"}},
	{ID: "mssql-remote-access", Section: "2.7", Title: "'remote access' is disabled", Severity: "low",
		Query: "SELECT CAST(value_in_use AS INT) v FROM sys.configurations WHERE name='remote access'", Expect: vaExpect{Op: "equals", Column: "v", Value: "0"},
		Remediation: "EXEC sp_configure 'remote access',0; RECONFIGURE;",
		Refs: []string{"CIS SQL Server §2.7"}},
	{ID: "mssql-remote-admin", Section: "2.8", Title: "'remote admin connections' is disabled", Severity: "low",
		Query: "SELECT CAST(value_in_use AS INT) v FROM sys.configurations WHERE name='remote admin connections'", Expect: vaExpect{Op: "equals", Column: "v", Value: "0"},
		Remediation: "EXEC sp_configure 'remote admin connections',0; RECONFIGURE;",
		Refs: []string{"CIS SQL Server §2.8"}},
	{ID: "mssql-default-trace", Section: "5.1", Title: "'default trace enabled' is on", Severity: "low",
		Query: "SELECT CAST(value_in_use AS INT) v FROM sys.configurations WHERE name='default trace enabled'", Expect: vaExpect{Op: "equals", Column: "v", Value: "1"},
		Remediation: "EXEC sp_configure 'default trace enabled',1; RECONFIGURE; — retains security-relevant events.",
		Refs: []string{"CIS SQL Server §5.1", "PCI-DSS 10.2"}},

	// Logins & roles
	{ID: "mssql-sa-disabled", Section: "3.x", Title: "'sa' login is disabled", Severity: "high",
		Query: "SELECT is_disabled FROM sys.server_principals WHERE sid=0x01", Expect: vaExpect{Op: "equals", Column: "is_disabled", Value: "1"},
		Remediation: "ALTER LOGIN [sa] DISABLE; — disable (or rename) the well-known sa account.",
		Refs: []string{"CIS SQL Server §3", "PCI-DSS 2.1"}},
	{ID: "mssql-empty-login-pw", Section: "3.x", Title: "No SQL login has an empty password", Severity: "critical",
		Query: "SELECT name FROM sys.sql_logins WHERE PWDCOMPARE('', password_hash)=1", Expect: vaExpect{Op: "rowsZero"},
		Remediation: "ALTER LOGIN [<name>] WITH PASSWORD='<strong>'; or drop the login.",
		Refs: []string{"CIS SQL Server §3", "PCI-DSS 8.3.1"}},
	{ID: "mssql-check-policy", Section: "4.x", Title: "SQL logins enforce password policy (CHECK_POLICY)", Severity: "medium",
		Query: "SELECT name FROM sys.sql_logins WHERE is_policy_checked=0 AND name NOT LIKE '##%'", Expect: vaExpect{Op: "rowsZero"},
		Remediation: "ALTER LOGIN [<name>] WITH CHECK_POLICY=ON; — enforce complexity/lockout.",
		Refs: []string{"CIS SQL Server §4", "PCI-DSS 8.3.6"}},
	{ID: "mssql-check-expiration", Section: "4.x", Title: "SQL logins enforce password expiration", Severity: "low",
		Query: "SELECT name FROM sys.sql_logins WHERE is_expiration_checked=0 AND name NOT LIKE '##%'", Expect: vaExpect{Op: "rowsZero"},
		Remediation: "ALTER LOGIN [<name>] WITH CHECK_EXPIRATION=ON;",
		Refs: []string{"CIS SQL Server §4", "PCI-DSS 8.3.9"}},
	{ID: "mssql-sysadmin-members", Section: "3.x", Title: "sysadmin role membership limited", Severity: "medium",
		Query: "SELECT p.name FROM sys.server_role_members m JOIN sys.server_principals p ON p.principal_id=m.member_principal_id JOIN sys.server_principals r ON r.principal_id=m.role_principal_id WHERE r.name='sysadmin' AND p.name<>'sa' AND p.name NOT LIKE '##%' AND p.name NOT LIKE 'NT SERVICE%' AND p.name NOT LIKE 'NT AUTHORITY%'",
		Expect:      vaExpect{Op: "rowsZero"},
		Remediation: "ALTER SERVER ROLE sysadmin DROP MEMBER [<name>]; — grant least privilege instead.",
		Refs:        []string{"CIS SQL Server §3", "PCI-DSS 7.2"}},
}

// ── Oracle Database (CIS Oracle Benchmark) ───────────────────────────────────
// Parameter checks read v$parameter; account/privilege checks read DBA_* views — both need
// SELECT_CATALOG_ROLE (or equivalent) and degrade to "error" otherwise.
var oracleVaChecks = []vaCheck{
	{ID: "ora-remote-os-authent", Section: "2.2.x", Title: "remote_os_authent is FALSE", Severity: "high",
		Query: "SELECT value FROM v$parameter WHERE name='remote_os_authent'", Expect: vaExpect{Op: "equals", Column: "value", Value: "FALSE"},
		Remediation: "ALTER SYSTEM SET remote_os_authent=FALSE SCOPE=SPFILE; — prevents OS-trusted remote logins.",
		Refs: []string{"CIS Oracle §2", "PCI-DSS 8.3"}},
	{ID: "ora-sec-case-logon", Section: "2.2.x", Title: "sec_case_sensitive_logon is TRUE", Severity: "medium",
		Query: "SELECT value FROM v$parameter WHERE name='sec_case_sensitive_logon'", Expect: vaExpect{Op: "equals", Column: "value", Value: "TRUE"},
		Remediation: "ALTER SYSTEM SET sec_case_sensitive_logon=TRUE SCOPE=SPFILE;",
		Refs: []string{"CIS Oracle §2"}},
	{ID: "ora-sql92-security", Section: "2.2.x", Title: "sql92_security is TRUE", Severity: "medium",
		Query: "SELECT value FROM v$parameter WHERE name='sql92_security'", Expect: vaExpect{Op: "equals", Column: "value", Value: "TRUE"},
		Remediation: "ALTER SYSTEM SET sql92_security=TRUE SCOPE=SPFILE; — require column privileges for WHERE.",
		Refs: []string{"CIS Oracle §2"}},
	{ID: "ora-audit-trail", Section: "2.2.x", Title: "Database auditing is enabled (audit_trail)", Severity: "medium",
		Query: "SELECT value FROM v$parameter WHERE name='audit_trail'", Expect: vaExpect{Op: "notEquals", Column: "value", Value: "NONE"},
		Remediation: "ALTER SYSTEM SET audit_trail=DB SCOPE=SPFILE; (or use Unified Auditing).",
		Refs: []string{"CIS Oracle §2", "PCI-DSS 10.2"}},
	{ID: "ora-remote-listener", Section: "2.2.x", Title: "remote_listener is empty", Severity: "medium",
		Query: "SELECT value FROM v$parameter WHERE name='remote_listener'", Expect: vaExpect{Op: "empty", Column: "value"},
		Remediation: "ALTER SYSTEM SET remote_listener='' SCOPE=SPFILE; — avoid registering with remote listeners.",
		Refs: []string{"CIS Oracle §2"}},
	{ID: "ora-max-failed-login", Section: "2.2.x", Title: "sec_max_failed_login_attempts <= 10", Severity: "medium",
		Query: "SELECT value FROM v$parameter WHERE name='sec_max_failed_login_attempts'", Expect: vaExpect{Op: "lte", Column: "value", Value: "10"},
		Remediation: "ALTER SYSTEM SET sec_max_failed_login_attempts=3 SCOPE=SPFILE;",
		Refs: []string{"CIS Oracle §2", "PCI-DSS 8.3.4"}},
	{ID: "ora-resource-limit", Section: "2.2.x", Title: "resource_limit is TRUE (profiles enforced)", Severity: "low",
		Query: "SELECT value FROM v$parameter WHERE name='resource_limit'", Expect: vaExpect{Op: "equals", Column: "value", Value: "TRUE"},
		Remediation: "ALTER SYSTEM SET resource_limit=TRUE; — enforces profile password/resource limits.",
		Refs: []string{"CIS Oracle §2"}},

	// Accounts & privileges (DBA_* views)
	{ID: "ora-default-passwords", Section: "1.x", Title: "No accounts use a known default password", Severity: "critical",
		Query: "SELECT username FROM dba_users_with_defpwd WHERE username NOT IN ('XS$NULL')", Expect: vaExpect{Op: "rowsZero"},
		Remediation: "ALTER USER <u> IDENTIFIED BY <strong-password>; — change any default-credential account.",
		Refs: []string{"CIS Oracle §1", "PCI-DSS 2.1"}},
	{ID: "ora-dba-role", Section: "4.x", Title: "DBA role not granted to non-system users", Severity: "high",
		Query: "SELECT grantee FROM dba_role_privs WHERE granted_role='DBA' AND grantee NOT IN ('SYS','SYSTEM')", Expect: vaExpect{Op: "rowsZero"},
		Remediation: "REVOKE DBA FROM <grantee>; — grant only the specific privileges required.",
		Refs: []string{"CIS Oracle §4", "PCI-DSS 7.2"}},
	{ID: "ora-public-utl", Section: "4.x", Title: "PUBLIC lacks EXECUTE on network/OS packages", Severity: "high",
		Query: "SELECT table_name FROM dba_tab_privs WHERE grantee='PUBLIC' AND privilege='EXECUTE' AND table_name IN ('UTL_FILE','UTL_TCP','UTL_HTTP','UTL_SMTP','DBMS_ADVISOR')",
		Expect:      vaExpect{Op: "rowsZero"},
		Remediation: "REVOKE EXECUTE ON <pkg> FROM PUBLIC; — these packages enable file/network access.",
		Refs:        []string{"CIS Oracle §4"}},
	{ID: "ora-any-privs", Section: "4.x", Title: "No non-system user holds '%ANY%' system privileges", Severity: "medium",
		Query: "SELECT grantee FROM dba_sys_privs WHERE privilege LIKE '%ANY%' AND grantee NOT IN ('SYS','SYSTEM','DBA','IMP_FULL_DATABASE','EXP_FULL_DATABASE','DATAPUMP_IMP_FULL_DATABASE','OEM_MONITOR')",
		Expect:      vaExpect{Op: "rowsZero"},
		Remediation: "REVOKE <ANY privilege> FROM <grantee>; — ANY privileges span every schema.",
		Refs:        []string{"CIS Oracle §4", "PCI-DSS 7.2"}},
	{ID: "ora-pw-life-time", Section: "3.x", Title: "DEFAULT profile PASSWORD_LIFE_TIME is limited", Severity: "medium",
		Query: "SELECT limit FROM dba_profiles WHERE profile='DEFAULT' AND resource_name='PASSWORD_LIFE_TIME'", Expect: vaExpect{Op: "notEquals", Column: "limit", Value: "UNLIMITED"},
		Remediation: "ALTER PROFILE DEFAULT LIMIT PASSWORD_LIFE_TIME 90;",
		Refs: []string{"CIS Oracle §3", "PCI-DSS 8.3.9"}},
	{ID: "ora-failed-login-attempts", Section: "3.x", Title: "DEFAULT profile FAILED_LOGIN_ATTEMPTS is limited", Severity: "medium",
		Query: "SELECT limit FROM dba_profiles WHERE profile='DEFAULT' AND resource_name='FAILED_LOGIN_ATTEMPTS'", Expect: vaExpect{Op: "notEquals", Column: "limit", Value: "UNLIMITED"},
		Remediation: "ALTER PROFILE DEFAULT LIMIT FAILED_LOGIN_ATTEMPTS 5;",
		Refs: []string{"CIS Oracle §3", "PCI-DSS 8.3.4"}},
	{ID: "ora-pw-reuse-max", Section: "3.x", Title: "DEFAULT profile PASSWORD_REUSE_MAX is limited", Severity: "low",
		Query: "SELECT limit FROM dba_profiles WHERE profile='DEFAULT' AND resource_name='PASSWORD_REUSE_MAX'", Expect: vaExpect{Op: "notEquals", Column: "limit", Value: "UNLIMITED"},
		Remediation: "ALTER PROFILE DEFAULT LIMIT PASSWORD_REUSE_MAX 20;",
		Refs: []string{"CIS Oracle §3"}},
}
